***NumPy***

In [1]:
import numpy as np

In [2]:
# creation
arr = np.array([[1,2,3],[4,5,6]])
arr = np.zeros(10)
arr = np.ones(10)
arr = np.arange(1,10,1) # start,stop,step
arr = np.linspace(1,30,num=20,dtype=int)
arr = np.random.randint(1,20,2)
print(arr)

[11 11]


In [3]:
# inspection
print(arr.shape)
print(arr.ndim) # no. of array dimensions
print(type(arr))
print(arr.dtype)
print(arr.size)

(2,)
1
<class 'numpy.ndarray'>
int64
2


In [15]:
#2D
c = np.array([[1,2,3],[2,3,1]])
print(c)
print(type(c))

#3D
d = np.array([[[1,2,3],[3,2,1]],[[1,2,0],[3,2,1]]])
print(d)
print(type(d))

[[1 2 3]
 [2 3 1]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [3 2 1]]

 [[1 2 0]
  [3 2 1]]]
<class 'numpy.ndarray'>


In [23]:
# manipulation
arr = np.linspace(1,20,num=9,dtype=int)
arrNew = np.linspace(1,20,num=3,dtype=int)
arr = arr.reshape(3,3)
arr = arr.flatten()
arr = np.concatenate((arr,arrNew),axis=0)
arr = arr.astype(float)
print(arr)

arr = arr.reshape(4,3)
print(arr)
arr = np.transpose(arr)
print(arr)

[ 1.  3.  5.  8. 10. 12. 15. 17. 20.  1. 10. 20.]
[[ 1.  3.  5.]
 [ 8. 10. 12.]
 [15. 17. 20.]
 [ 1. 10. 20.]]
[[ 1.  8. 15.  1.]
 [ 3. 10. 17. 10.]
 [ 5. 12. 20. 20.]]


In [18]:
# operations on numpy array
a = np.linspace(10,20,num = 10,dtype = np.int64)
b = np.linspace(1,10,num = 10,dtype = np.int32)

print(a)
print(b)
print(a*2)
print(a**2)
print(a/2)
print(a+1)
print(a-1)
print(a-b) #np.subtract(a,b)
print(a+b) #np.add(a,b)
print(a/b) #np.divide(a,b)
print(a*b) #np.multiply(a,b)

c = b**2
d = np.sqrt(c)
E = np.exp(d)
f = np.log(E)

print(a>15)
print(d==f)

[10 11 12 13 14 15 16 17 18 20]
[ 1  2  3  4  5  6  7  8  9 10]
[20 22 24 26 28 30 32 34 36 40]
[100 121 144 169 196 225 256 289 324 400]
[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.  10. ]
[11 12 13 14 15 16 17 18 19 21]
[ 9 10 11 12 13 14 15 16 17 19]
[ 9  9  9  9  9  9  9  9  9 10]
[11 13 15 17 19 21 23 25 27 30]
[10.          5.5         4.          3.25        2.8         2.5
  2.28571429  2.125       2.          2.        ]
[ 10  22  36  52  70  90 112 136 162 200]
[False False False False False False  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]


In [24]:
#ravel #insert #delete
a = np.linspace(1,20,num = 20).reshape(4,5)
print(a)
a = a.ravel() # flatten alternative
print(a)
a = np.insert(a,5,100) # array, pos, element
print(a)
a = np.delete(a,[4,5])
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[  1.   2.   3.   4.   5. 100.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20.]


In [15]:
# Aggregate/Functions
x = np.linspace(1,100,num = 60,dtype = np.int32).reshape(30,2)
print(x.sum(axis = 0))
print(x)
print(np.max(x))
print(np.min(x))
print(x.max(axis = 0))  # max in 2-D
print(x.sum(axis = 0))
x1 = np.random.random((1,2))
print(x1)
np.round(x1)
np.ceil(x1)
np.floor(x1)
x2 = np.random.permutation(np.arange(1, 100))
print(x2)
print(np.sort(x2))

[1475 1526]
[[  1   2]
 [  4   6]
 [  7   9]
 [ 11  12]
 [ 14  16]
 [ 17  19]
 [ 21  22]
 [ 24  26]
 [ 27  29]
 [ 31  32]
 [ 34  36]
 [ 37  39]
 [ 41  42]
 [ 44  46]
 [ 47  49]
 [ 51  53]
 [ 54  56]
 [ 58  59]
 [ 61  63]
 [ 64  66]
 [ 68  69]
 [ 71  73]
 [ 74  76]
 [ 78  79]
 [ 81  83]
 [ 84  86]
 [ 88  89]
 [ 91  93]
 [ 94  96]
 [ 98 100]]
100
1
[ 98 100]
[1475 1526]
[[0.53310401 0.57327341]]
[98 36 18 59 10 31 20 60 56 66 89 97  2 48  3  4 88 94 21 50 78 90 16 27
 29 71 84 85 76 83 63 32 26 42 58 22 82 23 55 44 99 39  7 81 87 70 65 54
  8 49 64 30 62 14 37 86 28 45 11 53 15 47 19 68 61 74 12 57 95 33 35  6
 52 43 79 80 92 17 91 38  5 41 75  9 93 34 96 73 13 46 40 69 77 51  1 24
 72 25 67]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 9

In [20]:
# slicing and indexing
a = np.arange(0,9).reshape(3,3)
print(a)
# print(a[1,2])
# print(a[[0,1,2],[0,0,0]])
# print(a[:2,0])
# a[a<7]
print(a[:,:2])
# a[2,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]
 [6 7]]


In [ ]:
#broadcasting

# !-- No error

a = np.arange(9).reshape(3,3)
b = np.arange(3).reshape(3)

print(a)
print(b)
print(a+b)


# !-- error

a1 = np.arange(3).reshape(1,3)
b1 = np.arange(3).reshape(3,2)

print(a1)
print(b1)
print(a1+b1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


ValueError: ignored

In [35]:
#stacking and splitting
a = np.linspace(1,10,num = 4,dtype =np.int32).reshape(2,2)
b = np.linspace(10,20,num = 6,dtype = np.int32).reshape(2,3)
print(a)
print(b)
print(np.hstack((a,b))) # require same number of column
# print(np.vstack((a,b))) # require same number of rows
b = np.array([1,2,3,4,5,6])
print(np.split(b,3)) # no of splits
# print(np.vsplit(c,2))

[[ 1  4]
 [ 7 10]]
[[10 12 14]
 [16 18 20]]
[[ 1  4 10 12 14]
 [ 7 10 16 18 20]]
[array([1, 2]), array([3, 4]), array([5, 6])]
